packages:
  - ".pkgs/*"
  - "apps/*"
  - "packages/*"
  # - "packages/*/*"
  - "examples/*"
onlyBuiltDependencies:
  - core-js
  - dprint
  - esbuild
overrides:
  "@eslint/js": "^10.0.0"
  "esbuild": "^0.27.3"
  "eslint": "^10.0.0"
  "tslib": "^2.8.1"
  "typescript": "^5.9.3"
