packages:
  - ".pkgs/*"
  - "apps/*"
  - "packages/*"
  - "packages/*/*"
  - "examples/*"
allowBuilds:
  dprint: true
  esbuild: true
  msgpackr-extract: true
onlyBuiltDependencies:
  - core-js
  - dprint
  - esbuild
  - msgpackr-extract
overrides:
  "esbuild": "^0.28.0"
  "tslib": "^2.8.1"
  "typescript": "^6.0.3"
  "undici": "^8.3.0"

# trustPolicy: "no-downgrade"
